# Site settings
title: James Baghurst | AI Engineer
description: James Baghurst's AI Engineering Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: James Baghurst
user_description: I am an AI engineer from Oxford with years of experience building full-stack AI systems and advanced user interfaces.
user_title: AI Engineer
email: jamesbaghurst@gmail.com
twitter_username: experilearning
github_username: bjsi

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
